name: Publish & Release
on:
  push:
    tags:
      - 'v*'
jobs:
  def:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    env:
      TZ: Asia/Shanghai
      PUB_NAME: script_def
    if: startsWith(github.ref, 'refs/tags/v')
    # if 条件其实和上边 on.push.tags 重复了，按需使用其中之一就可以
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v6
      # Build Release
      - name: Copy && Gen ZIP
        env:
          PUB_NAME: ${{ env.PUB_NAME }}
        run: |
          TMP_DIR=release_template
          rm -rf ${TMP_DIR}
          cp -r template ${TMP_DIR}
          rm -rf ${TMP_DIR}/output
          find ${TMP_DIR} -type d -name node_modules -prune -exec rm -rf '{}' +
          tar -czvf ${PUB_NAME}.tar.gz --transform 's,^release_template,template,' ${TMP_DIR}
          rm -rf ${TMP_DIR}
      # Get Tag For Release
      - name: Get Tag
        id: get_tag
        env:
          REF: ${{ github.ref }} # e.g. refs/tags/v1.0.0
        run: |
          TAG=${REF/refs\/tags\/v}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
      # Publish Release
      - name: Publish Release
        id: release
        uses: softprops/action-gh-release@v3
        env:
          TAG: ${{ steps.get_tag.outputs.tag }} # 获取上一步截取到的版本号，既 1.0.0
        with:
          name: template scaffold build v${{ env.TAG }}
          body: |
            template + gm-base scaffold package for rollup-plugin-monkey.

            Quick start:
            1. tar -xzvf script_def.tar.gz
            2. cd template && pnpm install
            3. pnpm run gen:gm
          files: ${{ env.PUB_NAME }}.tar.gz
      # Setup pnpm + Node
      - name: Setup pnpm
        uses: pnpm/action-setup@v5
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: pnpm
      # pnpm Publish
      - name: Install & Build & Publish
        run: |
          pnpm install --frozen-lockfile
          pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
