name: Publish & Release
on:
  push:
    tags:
      - "v*"
jobs:
  def:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    env:
      TZ: Asia/Shanghai
      PUB_NAME: script_def
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Build Release
      - name: Copy && Gen ZIP
        env:
          PUB_NAME: ${{ env.PUB_NAME }}
        run: |
          rm -rf ${PUB_NAME}
          cp -r test/gm ${PUB_NAME}
          cp test/.eslintrc.yaml ${PUB_NAME}/
          rm -rf
          sed -i "s/..\/..\/dist\/index.mjs/rollup-plugin-monkey/" ${PUB_NAME}/rollup.config.mjs
          sed -i "s/for test/for prod/" ${PUB_NAME}/rollup.config.mjs
          tar -czvf ${PUB_NAME}.tar.gz ${PUB_NAME}
      # Get Tag For Release Name
      - name: Get Tag
        id: get_tag
        env:
          REF: ${{ github.ref }}
        run: |
          TAG=${REF/refs\/tags\/v}
          echo "::set-output name=tag::${TAG}"
      # Publish Release
      - name: Publish Release
        id: release
        uses: softprops/action-gh-release@v1
        env:
          TAG: ${{ steps.get_tag.outputs.tag }}
        with:
          name: ${{ env.PUB_NAME }} Build ${{ env.TAG }}
          body: ${{ env.PUB_NAME }} Build ${{ env.TAG }} Release.
          files: ${{ env.PUB_NAME }}.tar.gz
      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      # NPM Publish
      - name: Install & Build & Publish
        run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
